/** @type {import('tailwindcss').Config} */
module.exports = {
    future: {
        hoverOnlyWhenSupported: true,
    },
    content: ["./src/**/*.{js,ts,jsx,tsx}"],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                primary: "#0284c7",
                secondary: "#6366f1",
                gold: "#D4AF37",
                silver: "#C0C0C0",
                gray: "#94a3b8",
                light: "#f5f5f5",
                "light-2": "#e5e5e5",
                "light-3": "#d4d4d4",
                dark: "#0f172a",
                "dark-2": "#1e293b",
                "dark-3": "#374151",
                "dark-4": "#3f3f46",
                att: "#ea580c",
                hp: "#e11d48",
                def: "#1d4ed8",
                spa: "#dc2626",
                spd: "#a21caf",
                spe: "#16a34a",
                normal: "#A8A77A",
                fire: "#EE8130",
                water: "#6390F0",
                electric: "#F7D02C",
                grass: "#7AC74C",
                ice: "#96D9D6",
                fighting: "#C22E28",
                poison: "#A33EA1",
                ground: "#E2BF65",
                flying: "#A98FF3",
                psychic: "#F95587",
                bug: "#A6B91A",
                rock: "#B6A136",
                ghost: "#735797",
                dragon: "#6F35FC",
                darkType: "#705746",
                steel: "#B7B7CE",
                fairy: "#D685AD",
            },
        },
        screens: {
            xs: "425px",
            sm: "640px",
            md: "768px",
            lg: "1024px",
            xl: "1280px",
            "2xl": "1536px",
        },
    },
    plugins: [require("tailwindcss-inner-border")],
}
