import Navbar from './navbar'
import Head from 'next/head'

interface Props {
    children: JSX.Element
}

export default function Layout({ children }: Props) {
    return (
        <div className="dark">
            <Head>
                <title>Team Builder</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main>{children}</main>
        </div>
    )
}
